name: Run test

on:
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - 'testmon/**'
      - 'tests/**'
      - '.coveragerc'
      - 'setup.cfg'
      - 'setup.py'


jobs:
  tests:
    name: Run test
    if: |
      github.event.pull_request.draft == false &&
      github.base_ref == 'main' &&
      github.event.pull_request.base.repo.full_name == 'hpcaitech/pytest-testmon'
    runs-on: [self-hosted, gpu]
    container:
      image: hpcaitech/pytorch-cuda:1.12.0-11.3.0
      options: --gpus all --rm
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Testmon
        uses: actions/checkout@v2

      - name: Install Testmon
        run: |
          pip install .

      - name: Execute Test
        run: |
          ./tests/test.sh
